package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Artists;
import ba.unsa.etf.rpr.domain.Artwork;
import ba.unsa.etf.rpr.exceptions.DBException;
import javafx.collections.ObservableList;

import java.time.LocalDate;
import java.time.Year;
import java.util.List;

public class ArtworkManager {

    public void validateName(String name) throws DBException {
        if (name == null || name.length() > 50 || name.length() < 1){
            throw new DBException("Name cannot be longer than 50 or shorter than 1 character!");
        }
    }
    public void validateEra(String era) throws DBException {
        if (era == null || era.length() > 50 || era.length() < 1){
            throw new DBException("Name of an era cannot be longer than 50 or shorter than 1 character!");
        }
    }

    public void validatePrice(double price) throws DBException {
        if (price <= 0 ){
            throw new DBException("Price cannot be zero or negative!");
        }
    }



    public Artwork add(Artwork a) throws DBException {
        if (a.getId() != 0){
            throw new DBException("You cannot add a new artwork containing ID. ID is autogenerated");
        }
        validateName(a.getName());
        validateEra(a.getEra());
        validatePrice(a.getPrice());

        try{
            return DaoFactory.artworkDao().add(a);
        }
        catch (DBException exc){
            //ovo???
            if (exc.getMessage().contains("UQ_NAME")){
                throw new DBException("Artwork with the same name already exists");
            }
            throw exc;
        }
    }

    public void delete(int artworkId) throws DBException{
        try{
            DaoFactory.artworkDao().delete(artworkId);
        }
        catch (DBException e){
            if (e.getMessage().contains("FOREIGN KEY")){
                throw new DBException("First delete related items before deleting these rows.");
            }
            throw e;
        }

    }

    public Artwork update(Artwork a) throws DBException{
        validateName(a.getName());
        validateEra(a.getEra());
        validatePrice(a.getPrice());
        return DaoFactory.artworkDao().update(a);
    }

    public List<Artwork> getAll() throws DBException{
        return DaoFactory.artworkDao().getAll();
    }


   /* public ObservableList<Artwork> getName() {
    }*/
}
